config/routes.rb
Rails.application.routes.draw do

  resources :workdays
  root 'welcome#index'

end

app/models/workday.rb
class Workday < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workdays_controller.rb
class WorkdaysController < ApplicationController
    def new
    end

    def create
        @workday = Workday.new(workday_params)

        @workday.save
        redirect_to @workday
    end

    def show
        @workday = Workday.find(params[:id])
    end

    private
    def workday_params
        params.require(:workday).permit(:day, :arrivaltime, :lunch, :lunchleave, :lunchback, :departuretime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workdays_helper.rb
module WorkdaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workdays</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Meus dias de trabalho ♡ </h1>

app/views/workdays/new.html.erb
<h1>Adicionar Dia de Trabalho ♬</h1>
<%= form_for :workday, url: workdays_path do |f| %>
    <p>
        <%= f.label :day, "Dia" %> <br>
        <%= f.date_field(:day) %>
    </p>
    <p>
        <%= f.label :arrivaltime, "Hora de chegada" %><br>
        <%= f.datetime_field(:arrivaltime) %>
    </p>
    <p>
    <%= f.check_box(:lunch) %>
    <%= f.label(:lunch, "Eu fui comer.") %>
    </p>
    <p class="lunch_time">
        <%= f.label :lunchleave, "Hora de saída pro almoço" %><br>
        <%= f.datetime_field(:lunchleave) %>
    </p>
    <p class="lunch_time">
        <%= f.label :lunchback, "Hora de volta do almoço" %><br>
        <%= f.datetime_field(:lunchback) %>
    </p>
    <p>
        <%= f.label :departuretime, "Hora de saída" %><br>
        <%= f.datetime_field(:departuretime) %>
    </p>
    <p>Hora estimada de saída</p>
    <div class="estimatedtime">

    </div>


    <p>
    <%= f.submit "Save" %>
    </p>
<% end %>

app/views/workdays/show.html.erb
<p>
Data:
<%= @workday.day %>
</p>
Hora de chegada:
<%= @workday.arrivaltime %>
<p>
</p>
Saiu para almoço?
<%= @workday.lunch %>
<p>
</p>
Hora de Saída:
<%= @workday.departuretime %>
<p>
Horas trabalhadas no dia:
<%= @workday.duration %>
</p>
<p>
</p>
<p>
</p>
<p>
</p>